### ISSUE TITLE
Negative Prompt Weights ( pika(chu) problem )

### ISSUE THREAD

**Issue by CapableWeb** [lstein/stable-diffusion#505] opened 2022-09-11 20:42 UTC
**Is your feature request related to a problem? Please describe.**

Trying to generate images of `pika` it seems SD gets confused and includes images of `pikachu` no matter what I try, so every image of pikas are some weird pika/pikachu hybrid

**Describe the solution you'd like**

My first idea was to just do `pika mammal`, but that doesn't seem to do the trick.

Second idea was to play with weights, like `pika:100 pikachu:0` but that seems to make SD even more likely to create pikachu hybrids.

Third idea, that I think this feature request is about, is to have negative weights, in order to avoid subjects. So something like `pika:100 pikachu:-100` would try its hardest to generate an image of a pika, while avoiding generating an image of pikachu.

**Additional context**

Initially [brought up on reddit](https://old.reddit.com/r/StableDiffusion/comments/xbivya/we_need_better_artiststyle_prompt_repository_tools/io09yt7/) over at the r/StableDiffusion subreddit. Thought I'd share a possible solution (although I don't know how realistic it is to actually implement it) and see if we can figure something out to solve the `pika(chu)` problem :)

**Comment by lstein** [comment] 2022-09-11 21:48
I enjoyed reproducing this bug. Those pika/pikachu hybrids are so cute! I have no idea whether your idea is feasible, but I'll tag @blessedcoolant and @bakkot for their insights.

**Comment by blessedcoolant** [comment] 2022-09-11 22:05
I believe that just pika gives you hybrids. So I didn't bother checking that.

But instead, I decided to give it a more accurate description of what I wanted.

```an image of a pika, a small, mountain-dwelling mammal found in Asia and North America```

This prompt gives me these results.

![000004 1941556609](https://user-images.githubusercontent.com/54517381/189550474-78444255-b41e-4161-8659-51ab340df644.png)
![000005 1807216376](https://user-images.githubusercontent.com/54517381/189550478-68233743-a9a0-4af6-bd5c-80c7b4fcb6cc.png)

But you can notice that there is slight yellow coloring because of Pikachu.

**But here's a thing I noticed about Stable Diffusion -- the words early in the prompt get the highest amount of importance. So I changed my prompt a little bit** 

```a small, mountain-dwelling mammal found in Asia and North America which is called a pika```

I moved pika to a later part in the prompt. And right so, I started getting proper images of Pikas.

![000007 84022810](https://user-images.githubusercontent.com/54517381/189550520-37a0e680-6131-4cde-879e-aec68ce9c576.png)

![000006 100319530](https://user-images.githubusercontent.com/54517381/189550526-19e23ab6-3013-43c3-8e4f-cdb66276f0bd.png)

----

So here's a couple of question we need to answer here.

1. We know Diffusion is only as good as the prompts. And it turns out even in cases like this, as long as the description is clear, the model does not get confused. So do we need to do anything about cases where the prompt is not clear? And what can we do about it? Because just like SD, there is no practical way for us to know what the user meant either without a clearer description.

2. Negative Weights: So weighted prompts basically do what I did above but in a more dynamic way. It sets up the model to get the power of the prompt words in a scaled order. So after far as my understanding of it goes, it is not possible for us to actually tell the model to ignore a particular entity from the prompt that has been given. The only way to really bypass that is to actually provide a clearer description. Bu I could be entirely wrong about this. And maybe @bakkot can shed light on if this is even possible.

**Comment by lstein** [comment] 2022-09-11 22:10
I see a little bit of pikachu yellow in the first couple of images, but I think you solved the problem in a very sensible way!

**Comment by blessedcoolant** [comment] 2022-09-11 22:39
There seem to be a lot of varieties of pikas with yellow fur too. In fact upon closer inspection, a lot of them seem to have a yellow tint on the under side of their bodies with the fur. Which is possibly why most images have the same impact.

[Image 1](https://www.treehugger.com/thmb/LBiHWccN4V45B1WqttISyWEmGJk=/1635x1635/smart/filters:no_upscale()/__opt__aboutcom__coeus__resources__content_migration__mnn__images__2017__08__american-pika-01-4545c0141cca4b4f9f72cb5443d9c726.jpg), [Image2](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM-ZtA8Tsi_T39YBhjzWL7dPSzbFcwjRqt1g&usqp=CAU), [Image 3](https://res.cloudinary.com/roundglass/image/upload/w_1104,h_736,c_fill/q_auto:best,f_auto/v1583996242/roundglass/sustain/Ladakh_Pika_Saurabh-Sawant-copy_eutgla.jpg)

This is not to say that the yellow might be from Pikachu but I feel we got pretty close. And I feel we can further tweak the prompt to make it even more accurate but I'm a little lost on my Pika knowledge to figure out what I need to do. :)

**Comment by hipsterusername** [comment] 2022-09-12 00:33
Cross Attention solves for this - https://github.com/bloc97/CrossAttentionControl

**Comment by tildebyte** [comment] 2022-09-12 02:30
I was struggling with this same issue today - it would be a Holy Grail if it existed :D

>  It sets up the model to get the power of the prompt words in a scaled order

I did not know this, and it explains a lot.

My hope is that either

- We're wrong and bakkot can fix it 😂

OR

- Cross-attention is the real solution

**Comment by Neosettler** [comment] 2022-09-12 18:20
A "Cross Attention Control" addition seems like a win.

**Comment by tildebyte** [comment] 2022-09-12 20:31
This is more fully addressed in #490, I've put it on the [ToDo tracker](https://github.com/lstein/stable-diffusion/discussions/195), and @Doggettx already has some commits in his fork.

**Closed** 2022-09-17 22:46 UTC
