### ISSUE TITLE
Original always gets saved when using -U with --from_file

### ISSUE THREAD

**Issue by n00mkrad** [lstein/stable-diffusion#388] opened 2022-09-05 15:59 UTC
**Describe your environment**
- GPU: RTX 3090
- VRAM: 24 GB
- CPU arch: x86_64
- OS: Windows 10
- Python: micromamba
- Branch: refactoring-simplet2i
- Commit: a515af5c349a085d969dd1e514133212f0984bc0

**Describe the bug**
Option --save_original is not used when using -U with --from_file, the original is always saved and this can't be disabled.

**To Reproduce**
1. Run prompts from a file with upscaling enabled
2. See that 1 iteration produces 2 images

**Expected behavior**
It should not save the original images (unless --save_original is used)

**Comment by lstein** [comment] 2022-09-05 17:55
Thanks. I’ll look into it.

**Comment by lstein** [comment] 2022-09-09 03:29
I can't reproduce the bug in the current development branch, so I think it was fixed with the recent rewrite. This will be pulled into main in a couple of days. Please feel free to file a new issue if the bug appears again.

**Closed by lstein** 2022-09-09 03:29 UTC
